version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
        - 9000:9000
    hostname: R710-01
    volumes:
        - /data/config/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=portainer.joshsamara.net
    networks:
      - bridgeRestrictIP
      
networks:
    bridgeRestrictIP:
        external: true